[package]
authors = ["Albert Abdulmanov <albert.abdu@gmail.com>"]
edition = "2018"
name = "converter"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6.2"
